# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nexusMsg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nexusMsg.proto',
  package='',
  serialized_pb=_b('\n\x0enexusMsg.proto\"\x08\n\x06Header\"J\n\x05Twist\x12\x17\n\x06header\x18\x01 \x01(\x0b\x32\x07.Header\x12\x0c\n\x04velX\x18\x02 \x02(\x02\x12\x0c\n\x04velY\x18\x03 \x02(\x02\x12\x0c\n\x04rotZ\x18\x04 \x02(\x02\"S\n\x08NexusMsg\x12\x17\n\x06header\x18\x01 \x01(\x0b\x32\x07.Header\x12\x16\n\x06\x63mdVel\x18\x02 \x01(\x0b\x32\x06.Twist\x12\x16\n\x06\x61\x63tVel\x18\x03 \x01(\x0b\x32\x06.Twist*0\n\x0bMessageType\x12\t\n\x05TWIST\x10\x01\x12\x0c\n\x08POSITION\x10\x02\x12\x08\n\x04ODOM\x10\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_MESSAGETYPE = _descriptor.EnumDescriptor(
  name='MessageType',
  full_name='MessageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TWIST', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POSITION', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ODOM', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=189,
  serialized_end=237,
)
_sym_db.RegisterEnumDescriptor(_MESSAGETYPE)

MessageType = enum_type_wrapper.EnumTypeWrapper(_MESSAGETYPE)
TWIST = 1
POSITION = 2
ODOM = 3



_HEADER = _descriptor.Descriptor(
  name='Header',
  full_name='Header',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=26,
)


_TWIST = _descriptor.Descriptor(
  name='Twist',
  full_name='Twist',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='Twist.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='velX', full_name='Twist.velX', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='velY', full_name='Twist.velY', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rotZ', full_name='Twist.rotZ', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=102,
)


_NEXUSMSG = _descriptor.Descriptor(
  name='NexusMsg',
  full_name='NexusMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='NexusMsg.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cmdVel', full_name='NexusMsg.cmdVel', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='actVel', full_name='NexusMsg.actVel', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=187,
)

_TWIST.fields_by_name['header'].message_type = _HEADER
_NEXUSMSG.fields_by_name['header'].message_type = _HEADER
_NEXUSMSG.fields_by_name['cmdVel'].message_type = _TWIST
_NEXUSMSG.fields_by_name['actVel'].message_type = _TWIST
DESCRIPTOR.message_types_by_name['Header'] = _HEADER
DESCRIPTOR.message_types_by_name['Twist'] = _TWIST
DESCRIPTOR.message_types_by_name['NexusMsg'] = _NEXUSMSG
DESCRIPTOR.enum_types_by_name['MessageType'] = _MESSAGETYPE

Header = _reflection.GeneratedProtocolMessageType('Header', (_message.Message,), dict(
  DESCRIPTOR = _HEADER,
  __module__ = 'nexusMsg_pb2'
  # @@protoc_insertion_point(class_scope:Header)
  ))
_sym_db.RegisterMessage(Header)

Twist = _reflection.GeneratedProtocolMessageType('Twist', (_message.Message,), dict(
  DESCRIPTOR = _TWIST,
  __module__ = 'nexusMsg_pb2'
  # @@protoc_insertion_point(class_scope:Twist)
  ))
_sym_db.RegisterMessage(Twist)

NexusMsg = _reflection.GeneratedProtocolMessageType('NexusMsg', (_message.Message,), dict(
  DESCRIPTOR = _NEXUSMSG,
  __module__ = 'nexusMsg_pb2'
  # @@protoc_insertion_point(class_scope:NexusMsg)
  ))
_sym_db.RegisterMessage(NexusMsg)


# @@protoc_insertion_point(module_scope)
